using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Contentful.Core;
using Contentful.Core.Configuration;
using Microsoft.AspNetCore.Html;
using Microsoft.Extensions.Logging.Abstractions;
using SFA.DAS.FindEmploymentSchemes.Contentful.Model.Content;
using SFA.DAS.FindEmploymentSchemes.Contentful.Services;

namespace SFA.DAS.FindEmploymentSchemes.Contentful.ContentCodeGenerator
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            var httpClient = new HttpClient();
            var client = new ContentfulClient(httpClient,
                new ContentfulOptions
                {
                    SpaceId = "082i50qdtar9",
                    DeliveryApiKey = "",
                    Environment = "master"
                });

            var contenfulClientFactory = new ContentfulClientFactory(new[] {client});

            var htmlRenderer = ContentService.CreateHtmlRenderer();

            var contentService = new ContentService(contenfulClientFactory, htmlRenderer, new NullLogger<ContentService>());

            var content = await contentService.Update();

            Console.Write(Preamble());

            GenerateSchemesContent(content.Schemes);

            GenerateFilterContent(content.MotivationsFilter);
            GenerateFilterContent(content.PayFilter);
            GenerateFilterContent(content.SchemeLengthFilter);

            GeneratePagesContent(content.Pages);

            Console.WriteLine(Closing());
        }

        private static void GeneratePagesContent(IEnumerable<Page> pages)
        {
            string typeName = GenerateProperty<Page>();

            foreach (var page in pages)
            {
                Console.WriteLine($"            new {typeName}(\"{page.Title}\",");
                Console.WriteLine($"                \"{page.Url}\",");
                Console.WriteLine($"                {GenerateHtmlString(page.Content)}");
                Console.WriteLine("            ),");
            }

            Console.WriteLine(@"        };");
        }

        private static void GenerateSchemesContent(IEnumerable<Scheme> schemes)
        {
            string typeName = GenerateProperty<Scheme>();

            Console.WriteLine(@"            // _    _                                _
            //| |  | |                              | |
            //| |__| | ___ _   _   _   _  ___  _   _| |
            //|  __  |/ _ \ | | | | | | |/ _ \| | | | |
            //| |  | |  __/ |_| | | |_| | (_) | |_| |_|
            //|_|  |_|\___|\__, |  \__, |\___/ \__,_(_)
            //              __/ |   __/ |
            //              |___/   |___/               
            //
            // these schemes are generated by the TestHarness from Contentful, so don't directly make changes here!!!
            //
");

            foreach (var scheme in schemes)
            {
                Console.WriteLine($"            new {typeName}(\"{scheme.Name}\",");
                Console.WriteLine($"                {GenerateHtmlString(scheme.ShortDescription)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.ShortCost)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.ShortBenefits)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.ShortTime)},");
                Console.WriteLine($"                \"{scheme.Url}\", {scheme.Size},");

                Console.Write("             new string[] {");
                Console.Write($"                {string.Join(", ", scheme.FilterAspects.Select(f => $"\"{f}\""))}");
                Console.WriteLine("             },");

                Console.WriteLine($"                {GenerateHtmlString(scheme.DetailsPageOverride)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.Description)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.Cost)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.Responsibility)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.Benefits)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.CaseStudies)},");
                Console.WriteLine($"                \"{scheme.OfferHeader}\",");
                Console.WriteLine($"                {GenerateHtmlString(scheme.Offer)},");
                Console.WriteLine($"                {GenerateHtmlString(scheme.AdditionalFooter)}");
                Console.WriteLine("                ),");
            }

            Console.WriteLine(@"        };");
        }

        private static void GenerateFilterContent(Filter filter)
        {
            string upperName = $"{char.ToUpperInvariant(filter.Name[0])}{filter.Name.Substring(1)}";

            Console.WriteLine($@"       private Filter? _{filter.Name}Filter;
        public Filter {upperName}Filter => _{filter.Name}Filter ??= new Filter(""{filter.Name}"", ""{filter.Description}"", new FilterAspect[]
        {{");

            foreach (var filterAspect in filter.Aspects)
            {
                Console.WriteLine($"            new FilterAspect(\"{filterAspect.Id}\", \"{filterAspect.Description}\"),");
            }

            Console.WriteLine("        });");
        }

        private static string Preamble()
        {
            return @"using System.Collections.Generic;
using Microsoft.AspNetCore.Html;
using SFA.DAS.FindEmploymentSchemes.Contentful.Model.Content;
using SFA.DAS.FindEmploymentSchemes.Contentful.Model.Content.Interfaces;

namespace SFA.DAS.FindEmploymentSchemes.Contentful.Content
{
    public class GeneratedContent : IContent
    {
";
        }

        private static string Closing()
        {
            return @"    }
}";
        }

        //todo: rename EnumerableProperty?
        private static string GenerateProperty<T>()
        {
            string typeName = typeof(T).Name;
            string backingName = $"_{char.ToLowerInvariant(typeName[0])}{typeName.Substring(1)}s";

            Console.WriteLine($@"        private IEnumerable<{typeName}>? {backingName};
        public IEnumerable<{typeName}> {typeName}s => {backingName} ??= new {typeName}[]
        {{");

            return typeName;
        }

        private static string GenerateHtmlString(HtmlString? content)
        {
            if (content == null)
                return "null";

            return $"new HtmlString(@\"{content.Value.Replace("\"", "\"\"")}\")";
        }
    }
}
