using Microsoft.AspNetCore.Html;
using SFA.DAS.FindEmploymentSchemes.Contentful.Model.Content;
using SFA.DAS.FindEmploymentSchemes.Contentful.Model.Content.Interfaces;
using SFA.DAS.FindEmploymentSchemes.Contentful.Model.Interim;
using System.Collections.Generic;

namespace SFA.DAS.FindEmploymentSchemes.Contentful.Content
{
    public class GeneratedContent : IContent
    {
        //  _    _                                _
        // | |  | |                              | |
        // | |__| | ___ _   _   _   _  ___  _   _| |
        // |  __  |/ _ \ | | | | | | |/ _ \| | | | |
        // | |  | |  __/ |_| | | |_| | (_) | |_| |_|
        // |_|  |_|\___|\__, |  \__, |\___/ \__,_(_)
        //               __/ |   __/ |
        //               |___/   |___/               
        //
        // this file is generated by the ContentCodeGenerator utility, so don't directly make changes here!!!
        //

        public IEnumerable<InterimPage> InterimPages
        {
            get
            {
                return new List<InterimPage>();
            }
        }

        public IEnumerable<InterimMenuItem> MenuItems
        {
            get
            {
                // If _interimLandingPage is null, initialize it with a new InterimLandingPage instance
                return new List<InterimMenuItem>()
                {

                    new InterimMenuItem() 
                    { 
                        
                        InterimMenuItemTitle = "Business Home - Menu Item",

                        InterimMenuItemText = "Business Home",

                        InterimMenuItemSource = "/",

                        InterimMenuItemOrder = 1
                    
                    }

                };
            }
        }

        private InterimLandingPage? _interimLandingPage;

        public InterimLandingPage? InterimLandingPage
        {
            get
            {
                // If _interimLandingPage is null, initialize it with a new InterimLandingPage instance
                return _interimLandingPage ??= new InterimLandingPage()
                {
                    InterimLandingPageID = "interim-landing-page",
                    InterimLandingPageTitle = "Interim Landing Page",
                    InterimLandingPagePreamble = new InterimPreamble() { PreambleTitle = "Landing Page Preamble" }
                };
            }
        }

        private IEnumerable<Scheme>? _schemes;
        public IEnumerable<Scheme> Schemes => _schemes ??= new Scheme[]
        {
            new Scheme("Apprenticeships",
                "",
                "Find out more about apprenticeships.",
                new HtmlString(@"<p class=""govuk-body"">Paid employment for over 16s, combining work and study in a job allowing you to develop your workforce and business.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Apprentice minimum wage and 5% training contribution depending on business size</p>"),
                new HtmlString(@"<p class=""govuk-body"">You develop a motivated, skilled and qualified workforce with knowledge of your business</p>"),
                new HtmlString(@"<p class=""govuk-body"">Minimum of 12 months employment</p>"),
                "Both",
                "16 and over",
                "Free or costed",
                "Over 1 year",
                "apprenticeships", 
                403000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--recruit-new-staff", "motivation--retrain-or-upskill-existing-staff", "duration--longer-than-1-year", "cost--may-require-employer-contribution" },
                new CaseStudy[] {
                    new CaseStudy("Apprenticeships - government incentives",
                    "How businesses are using government incentives to hire apprentices",
                    new HtmlString(@"<p class=""govuk-body""><strong>Paul Siniecki, Strategic Labour Needs and Training Manager at MTR Elizabeth line said:</strong></p><p class=""govuk-body"">We plan to continue to offer apprenticeship opportunities in 2021 and will be recruiting for the role of Customer Experience Assistant to work at the new stations in the Crossrail tunnel, and we will also be using the new &#39;Redundancy Support Service for Apprentices&#39;, who have been made redundant, for future apprenticeship opportunities, supporting those that have lost their job and giving them a new start.</p><p class=""govuk-body"">Read about <a href=""https://www.gov.uk/government/case-studies/how-employers-are-making-the-most-of-apprenticeship-incentives"" title="""" class=""govuk-link"">how employers are making the most of apprenticeship incentives</a></p>")
                    ),
                    new CaseStudy("Apprenticeships - employer",
                    "Smith & Williamson",
                    new HtmlString(@"<p class=""govuk-body"">Smith &amp; Williamson is among the ten largest firms of accountants in the UK. With a workforce of 1800, Smith and Williamson has 124 apprentices, in roles including Assurance &amp; Business Services, Business Tax and Private Client Tax. The firm merged with Tilney Group in September 2020 and is now part of the Tilney Smith and Williamson Group.</p>")
                    ),
                    new CaseStudy("Apprenticeships - what is the service video",
                    "What is the Apprenticeship service?",
                    new HtmlString(@"<p class=""govuk-body""><div class=""app-video-container"" style=""--aspect-ratio: 56.25%""><iframe width=""560"" height=""315"" src=""https://www.youtube-nocookie.com/embed/xWUFLAAc4TY"" title=""YouTube video player"" frameborder=""0"" allow=""accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"" allowfullscreen></iframe></div></p>")
                    ),
                },
                new HtmlString(@"<p class=""govuk-body"">Read how other businesses have used an apprenticeship scheme</p>"),
                null,
                "Offer an apprenticeship",
                new HtmlString(@"<h2 class=""govuk-heading-l""><strong>Scotland, Wales and Northern Ireland</strong></h2><p class=""govuk-body"">If you're an employer, you can contact the:</p><p class=""govuk-body""><a href=""https://www.apprenticeships.scot/"" title="""" class=""govuk-link"">Apprenticeship authority in Scotland</a></p><p class=""govuk-body""><a href=""https://businesswales.gov.wales/skillsgateway/apprenticeships"" title="""" class=""govuk-link"">Apprenticeship authority in Wales</a></p><p class=""govuk-body""><a href=""https://www.nidirect.gov.uk/campaigns/apprenticeships"" title="""" class=""govuk-link"">Apprenticeship authority in Northern Ireland</a></p>"),
                new SubScheme[] {
                }
                ),
            new Scheme("T Levels: industry placements",
                "T Levels",
                "Find about about T levels for employers",
                new HtmlString(@"<p class=""govuk-body"">Provide a 45-day (315 hours) industry placement for 16 to 19 year-olds, which gives you early access to the brightest young people entering the market and the opportunity to develop your workforce of the future.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Free government scheme but you may have your own business costs</p>"),
                new HtmlString(@"<p class=""govuk-body"">Allows you to grow your workforce in the short-term with little or no cost and scout future talent in your area</p>"),
                new HtmlString(@"<p class=""govuk-body"">Short term 45-day industry placement</p>"),
                "New",
                "16 to 19",
                "Free",
                "Under 1 year",
                "t-levels-industry-placements", 
                72000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--recruit-new-staff", "motivation--offer-short-terms-work-experience-placements", "duration--less-than-6-months", "cost--free" },
                new CaseStudy[] {
                },
                new HtmlString(@"<p class=""govuk-body"">Read about <a href=""https://www.gov.uk/government/case-studies/how-employers-are-benefitting-from-t-level-industry-placements"" title="""" class=""govuk-link"">how businesses are using T Levels industry placements</a>.</p>"),
                null,
                "Offer an industry placement",
                null,
                new SubScheme[] {
                }
                ),
            new Scheme("Sector-based Work Academy Programme (SWAP)",
                "SWAPs",
                "Find out more about SWAPs.",
                new HtmlString(@"<p class=""govuk-body"">Up to 6-week placement for benefit claimants for those aged 18 and over designed to help you recruit a workforce with the right skills to sustain and grow your business.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Free government scheme but you may have your own business costs</p>"),
                new HtmlString(@"<p class=""govuk-body"">Helps you recruit or train staff through fully-funded pre-employment training</p>"),
                new HtmlString(@"<p class=""govuk-body"">Up to 6-weeks</p>"),
                "New",
                "16 and over",
                "Free",
                "Under 1 year",
                "sector-based-work-academy-programme-swap", 
                70000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--recruit-new-staff", "motivation--offer-short-terms-work-experience-placements", "duration--less-than-6-months", "cost--free" },
                new CaseStudy[] {
                },
                new HtmlString(@"<p class=""govuk-body"">Read about <a href=""https://www.gov.uk/government/case-studies/how-employers-are-benefitting-from-sector-based-work-academies"" title="""" class=""govuk-link"">how employers are using sector-based work academy programmes</a>.</p>"),
                null,
                "Offer a SWAP",
                null,
                new SubScheme[] {
                }
                ),
            new Scheme("Skills Bootcamps",
                "",
                "Find out more about Skills Bootcamps.",
                new HtmlString(@"<p class=""govuk-body"">Flexible training courses for aged 19 and over to fast-track specialist skill development, for existing or new talent for your business.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Cost is dependent on the size of your business. There is no cost to the employer if the learner is not currently employed by you</p>"),
                new HtmlString(@"<p class=""govuk-body""> A new starter will be trained in a specialist skill specific to your business and be highly motivated by a guaranteed interview afterwards</p>"),
                new HtmlString(@"<p class=""govuk-body"">up to 16-weeks</p>"),
                "Both",
                "19s and over",
                "Free or costed",
                "Under 1 year",
                "skills-bootcamps", 
                68000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--recruit-new-staff", "motivation--retrain-or-upskill-existing-staff", "motivation--offer-short-terms-work-experience-placements", "duration--less-than-6-months", "cost--may-require-employer-contribution" },
                new CaseStudy[] {
                },
                null,
                null,
                "Offer a Skills Bootcamps",
                null,
                new SubScheme[] {
                }),
            new Scheme("Supported Internships for learners with an education, health and care plan",
                "SEND",
                "Supported internships for people with SEND.",
                new HtmlString(@"<p class=""govuk-body"">An unpaid 6 to 12-month work placement for 16 to 24-year-olds with additional needs, including Special Educational Needs and Disabilities (SEND), supported by a qualified job coach.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Free government scheme but you may have your own business costs</p>"),
                new HtmlString(@"<p class=""govuk-body"">Increases your confidence and ability to employ individuals with additional needs, improving and expanding your business' recruitment prospects</p>"),
                new HtmlString(@"<p class=""govuk-body"">6 to 12-months</p>"),
                "New",
                "16 to 24",
                "Free",
                "Under 1 year",
                "supported-internships", 
                20000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--offer-short-terms-work-experience-placements", "motivation--recruit-new-staff", "duration--between-6-months-and-1-year", "cost--free" },
                new CaseStudy[] {
                },
                null,
                null,
                "Offer a supported internship",
                null,
                new SubScheme[] {
                }
                ),
            new Scheme("Care-Leaver Covenant",
                "",
                "Explore the Care-leaver Covenant",
                new HtmlString(@"<p class=""govuk-body"">Help 16 to 25-year-olds who were in local authority care become independent through practical job-related support, in whatever way suits your business.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Free government scheme but you may have your own business costs related to the practical offer you make to care leavers</p>"),
                new HtmlString(@"<p class=""govuk-body"">Helping care-leavers to move to independent living and bring their life skills to enrich your business</p>"),
                new HtmlString(@"<p class=""govuk-body"">Length of time can vary</p>"),
                "New",
                "16 to 25",
                "Free",
                "Variable",
                "care-leaver-covenant", 
                2000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--recruit-new-staff", "duration--less-than-6-months", "duration--between-6-months-and-1-year", "duration--longer-than-1-year", "cost--free" },
                new CaseStudy[] {
                },
                new HtmlString(@"<p class=""govuk-body"">Read how <a href=""https://mycovenant.org.uk/covenant-stories/"" title="""" class=""govuk-link"">companies have been making a difference to the lives of care leavers</a></p>"),
                null,
                "Offer a Care Leavers Covenant",
                null,
                new SubScheme[] {
                }
                ),
            new Scheme("Employing prisoners and prison leavers",
                "",
                "Employing prisoners and prison leavers.",
                new HtmlString(@"<p class=""govuk-body"">Employ prisoners and prison leavers aged 18 and over to help your business fill skills gaps and develop a loyal and talented workforce.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Free government scheme but you may have your own business costs</p>"),
                new HtmlString(@"<p class=""govuk-body"">Access a workforce that is highly motivated to grow through work</p>"),
                new HtmlString(@"<p class=""govuk-body"">Variable depending on employer and prisoner and prison leaver</p>"),
                "New",
                "Ault prisoners",
                "Free",
                "Variable",
                "employing-prisoners-and-prison-leavers", 
                1000,
                new List<SchemeFilterAspect>(),
             new string[] { "motivation--recruit-new-staff", "duration--less-than-6-months", "duration--between-6-months-and-1-year", "duration--longer-than-1-year", "cost--free" },
                new CaseStudy[] {
                },
                new HtmlString(@"<p class=""govuk-body"">Read about <a href=""https://newfuturesnetwork.gov.uk/case-studies/#"" title="""" class=""govuk-link"">how businesses are working with serving prisoners and hiring prison leavers</a>.</p>"),
                null,
                "Offer prisoners and prison leavers employment",
                null,
                new SubScheme[] {
                }
                ),
            new Scheme("Free courses and additional training for your employees",
                "Free courses for jobs",
                "Free courses and additional training.",
                new HtmlString(@"<p class=""govuk-body"">Additional ways to train up existing employees through free qualifications, career advice and financial support.</p>"),
                "Benefits for your business",
                "Cost",
                "Duration",
                new HtmlString(@"<p class=""govuk-body"">Courses are fully funded for eligible adults but employees may need time to study and attend classes</p>"),
                new HtmlString(@"<p class=""govuk-body"">Help improve productivity, and develop a loyal and talented workforce in a rapidly changing labour market</p>"),
                new HtmlString(@"<p class=""govuk-body"">Length of time can vary</p>"),
                "Existing",
                "19 and over",
                "Free",
                "Variable",
                "free-courses-and-additional-training-for-your-employees", 
                -1000,
                new List<SchemeFilterAspect>()
                {

                    //new SchemeFilterAspect() { SchemeFilterAspectName = "" }

                },
             new string[] { "duration--less-than-6-months", "duration--between-6-months-and-1-year", "duration--longer-than-1-year", "cost--free", "motivation--retrain-or-upskill-existing-staff" },
                new CaseStudy[] {
                },
                null,
                null,
                "How to offer",
                null,
                new SubScheme[] {
                    new SubScheme("Higher Technical Qualifications (HTQs)",
                    new HtmlString(@"<p class=""govuk-body"">Higher Technical Qualifications (HTQs) are a high-quality addition to technical training routes, alongside apprenticeships, traineeships, and degrees.</p>"),
                    new HtmlString(@"<p class=""govuk-body"">HTQs have been developed by employers and awarding bodies to help you upskill existing employees and provide a different recruitment pool to hire new talent.</p><p class=""govuk-body"">You can support an employee to undertake an HTQ. The cost is dependent on the course and the provider.</p><p class=""govuk-body"">They are:</p><ul class=""govuk-list govuk-list--bullet""><li>new and existing Level 4 and 5 qualifications (such as Higher National Diplomas, Foundation Degrees, Diploma Higher Education)</li><li>approved by the Institute for Apprenticeships and Technical Education, against employer-led occupational standards</li><li>classroom based and do not require an in-work placement</li></ul><p class=""govuk-body"">The first Digital HTQs will be available for teaching from 2022, leading to higher-level occupations like Network Engineer, Software Developer and Data Analyst.</p><p class=""govuk-body"">Health and Science and Construction qualifications will be available for teaching from 2023, with a full roll-out of further industrial sectors over a four-year period.</p><h3 class=""govuk-heading-m"">Offer a HTQ</h3><p class=""govuk-body""><a href=""https://www.gov.uk/guidance/htqs"" title="""" class=""govuk-link"">Learn more and get started with HTQs.</a></p>")
                    ),
                    new SubScheme("Free training for basic skills (English, maths and digital)",
                    new HtmlString(@"<p class=""govuk-body"">Free English, maths, digital courses, and qualifications for adults.</p>"),
                    new HtmlString(@"<h3 class=""govuk-heading-m"">English and maths entitlement</h3><p class=""govuk-body"">In England, any adult who does not already have a level 2 qualification (GCSE grade 4 or equivalent) in English or maths is legally entitled to fully funded study up to level 2.ÿ</p><p class=""govuk-body"">Your workforce gets the potential to progress, and your business increases its productivity.</p><h3 class=""govuk-heading-m"">English for Speakers of Other Languages (ESOL)</h3><p class=""govuk-body"">Adults can be fully or part-funded to study for ESOL qualifications from entry-level to level 2.</p><p class=""govuk-body"">ESOL improves English language skills which provides a clear return for individuals and the economy.ÿ</p><p class=""govuk-body"">Full-funding is available through the Adult Education Budget (AEB) if individuals:</p><ul class=""govuk-list govuk-list--bullet""><li>are unemployed, looking for work and in receipt of certain benefits</li><li>in low-wage employmentÿ</li></ul><p class=""govuk-body"">Some AEB-eligible learners can have up to 50% of the course cost paid for through a Government contribution.</p><p class=""govuk-body"">In 9 Mayoral Combined Authorities (MCAs), AEB funding is allocated locally as well as in the Greater London Authority (GLA). Therefore, in these areas, eligibility may differ.ÿ</p>")
                    ),
                    new SubScheme("Free digital training",
                    null,
                    new HtmlString(@"<p class=""govuk-body"">Any adult with low digital skills is entitled to fully funded essential digital skills qualifications, at entry-level and level 1. These equip adults with the full range of essential digital skills needed for life, work, and further study.ÿ</p><p class=""govuk-body"">Funding for other digital skills qualifications may also be available but this will depend on local training providers.</p><p class=""govuk-body"">Find out more about free training courses at <a href=""https://skillsforlife.campaign.gov.uk/"" title="""" class=""govuk-link"">skills for life</a>.</p>")
                    ),
                    new SubScheme("Free level 3 qualifications for adults",
                    null,
                    new HtmlString(@"<p class=""govuk-body"">Free level 3 qualifications are government-funded courses for any adult aged 19 and over, who are looking to achieve a full level 3 qualification. You can also apply for the course if you have done a level 3 qualification before if you are unemployed or earning below national minimum wage.</p><p class=""govuk-body"">A full level 3 qualification is equivalent to an advanced technical certificate, diploma, or A levels.</p><p class=""govuk-body""><a href=""https://www.gov.uk/guidance/free-courses-for-jobs"" title="""" class=""govuk-link"">The Free Courses for jobs</a> offer and the qualification list has been developed with industry and will be regularly reviewed.</p>")
                    ),
                    new SubScheme("National Careers Service",
                    null,
                    new HtmlString(@"<p class=""govuk-body"">The National Careers Service is free to use and can help you explore work and skill opportunities for your workforce.</p><p class=""govuk-body"">Find out more about <a href=""https://nationalcareers.service.gov.uk/"" title="""" class=""govuk-link"">the National Careers Service and how to contact them</a>.</p>")
                    ),
                }
                ),
        };
        private List<SchemeFilter>? _schemeFilters;
        public List<SchemeFilter> SchemeFilters => _schemeFilters ??= new List<SchemeFilter>()
        {

            new SchemeFilter()
            {

                SchemeFilterName = "Scheme Filter - Motivation",

                SchemeFilterDescription = "I want to",

                SchemeFilterPrefix = "motivation",

                SchemeFilterOrder = 1,

                SchemeFilterAspects = new List<SchemeFilterAspect>()
                {

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Motivation - Recruit New Staff", SchemeFilterAspectPrefix = "motivation", SchemeFilterAspectName = "Recruit new staff", SchemeFilterAspectOrder = 1 },

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Motivation - Retrain or upskill existing staff", SchemeFilterAspectPrefix = "motivation", SchemeFilterAspectName = "Retrain or upskill existing staff", SchemeFilterAspectOrder = 2 },

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Motivation - Offer short terms work experience placements", SchemeFilterAspectPrefix = "motivation", SchemeFilterAspectName = "Offer short terms work experience placements", SchemeFilterAspectOrder = 3 }

                },

            },

            new SchemeFilter()
            {

                SchemeFilterName = "Scheme Filter - Duraton",

                SchemeFilterDescription = "Duration of scheme",

                SchemeFilterPrefix = "duration",

                SchemeFilterOrder = 2,

                SchemeFilterAspects = new List<SchemeFilterAspect>()
                {

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Duration - Less than 6 months", SchemeFilterAspectPrefix = "duration", SchemeFilterAspectName = "Less than 6 months", SchemeFilterAspectOrder = 1 },

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Duration - Between 6 months and 1 year", SchemeFilterAspectPrefix = "duration", SchemeFilterAspectName = "Between 6 months and 1 year", SchemeFilterAspectOrder = 2 },

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Duration - Longer than 1 year", SchemeFilterAspectPrefix = "duration", SchemeFilterAspectName = "Longer than 1 year", SchemeFilterAspectOrder = 3 }

                },

            },

            new SchemeFilter()
            {

                SchemeFilterName = "Scheme Filter - Cost",

                SchemeFilterDescription = "Cost of training",

                SchemeFilterPrefix = "cost",

                SchemeFilterOrder = 2,

                SchemeFilterAspects = new List<SchemeFilterAspect>()
                {

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Cost - Free", SchemeFilterAspectPrefix = "cost", SchemeFilterAspectName = "Free", SchemeFilterAspectOrder = 1 },

                    new SchemeFilterAspect(){ SchemeFilterAspectTitle = "SchemeFilterAspect - Cost - May require employer contribution", SchemeFilterAspectPrefix = "cost", SchemeFilterAspectName = "May require employer contribution", SchemeFilterAspectOrder = 2 }

                },

            }

        };

        private IEnumerable<Page>? _pages;
        public IEnumerable<Page> Pages => _pages ??= new Page[]
        {
            new Page("Environment",
                "environment",
                new HtmlString(@"<p class=""govuk-body"">master</p>")
            ),
            new Page("AnalyticsCookies",
                "analyticscookies",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Details about cookies</h1><p class=""govuk-body"">This service puts small files (known as &#39;cookies&#39;) onto your computer. These cookies are used to:</p><ul class=""govuk-list govuk-list--bullet""><li>help us understand how you use the website, so we can make improvements</li><li>remember what notifications you&#39;ve seen so you&#39;re not shown them more than once</li><li>temporarily store the selections you make</li></ul><p class=""govuk-body"">Find out more about&#160;<a href=""https://ico.org.uk/your-data-matters/online/cookies/"" title="""" class=""govuk-link"">how to manage cookies</a>.</p><h2 class=""govuk-heading-l"">Cookies that measure website usage</h2><p class=""govuk-body"">We use Google Analytics software (Universal Analytics) to collect anonymised information about how you use the service. We do this to help make sure the service is meeting the needs of its users and to help us make improvements.</p><p class=""govuk-body"">We do not allow Google to use or share the data about how you use this service.</p><p class=""govuk-body"">Google Analytics stores information about:</p><ul class=""govuk-list govuk-list--bullet""><li>how you got to the service</li><li>the pages you visit on this service and how long you spend on them</li><li>what you click on while you&#39;re visiting the service</li></ul><p class=""govuk-body"">We may also set our own cookies to understand how people move through the service.</p><p class=""govuk-body""></p>")
            ),
            new Page("MarketingCookies",
                "marketingcookies",
                new HtmlString(@"<h2 class=""govuk-heading-l"">Cookies that help with our communications and marketing</h2><p class=""govuk-body"">Some of our pages may contain content from other sites, like YouTube, which may set their own cookies. These sites are sometimes called &#39;third party&#39; services. This tells us how many people are seeing the content and whether it&#39;s useful.</p><p class=""govuk-body"">We also share information about your use of our pages with our social media and advertising partners (for example, Facebook) to help us improve the relevancy of advertising campaigns you receive from us.</p><p class=""govuk-body"">They may set cookies that you can turn off. Find out more about how to&#160;<a href=""https://ico.org.uk/your-data-matters/online/cookies/"" title="""" class=""govuk-link"">turn off these cookies</a>.</p><p class=""govuk-body"">In addition, if you share a link to one of our pages, the service you share it on (for example, Facebook) may set a cookie. We have no control over cookies set on other websites - you can turn them off, but not through us.</p><p class=""govuk-body""></p>")
            ),
            new Page("Accessibility statement",
                "accessibility-statement",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Accessibility statement</h1><p class=""govuk-body"">This accessibility statement applies to ""Find training and employment schemes for your business.""

This website is run by the Education and Skills Funding Agency. We want as many people as possible to be able to use this website. For example, that means you should be able to:</p><ul class=""govuk-list govuk-list--bullet""><li>
change colours, contrast levels and fonts
</li><li>zoom in up to 300% without the text spilling off the screen
</li><li>navigate most of the website using just a keyboard
</li><li>navigate most of the website using speech recognition software
</li><li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li></ul><p class=""govuk-body"">
We've also made the website text as simple as possible to understand.
<a href=""https://mcmw.abilitynet.org.uk/"" title="""" class=""govuk-link"">AbilityNet</a> has advice on making your device easier to use if you have a disability.

</p><h2 class=""govuk-heading-l"">
Feedback and contact information</h2><h2 class=""govuk-heading-l""></h2><p class=""govuk-body"">
If you need information on this website in a different format like accessible PDF, large print, easy read, audio recording or braille, email:
<a href=""ESFA.GOVUK-ENQUIRIES@education.gov.uk "" title="""" class=""govuk-link"">ESFA.GOVUK-ENQUIRIES@education.gov.uk </a>

We'll consider your request and get back to you in 5 working days.
</p><h2 class=""govuk-heading-l"">Reporting accessibility problems with this website</h2><p class=""govuk-body""></p><p class=""govuk-body"">
We're always looking to improve the accessibility of this website. 

If you find any problems not listed on this page or think we're not meeting accessibility requirements, contact: <a href=""ESFA.GOVUK-ENQUIRIES@education.gov.uk "" title="""" class=""govuk-link"">ESFA.GOVUK-ENQUIRIES@education.gov.uk</a>.
</p><h2 class=""govuk-heading-l"">Enforcement procedure
</h2><p class=""govuk-body"">The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the 'accessibility regulations'). 
</p><p class=""govuk-body"">If you're not happy with how we respond to your complaint, <a href=""https://www.equalityadvisoryservice.com/"" title="""" class=""govuk-link"">contact the Equality Advisory and Support Service (EASS)</a>.

</p><p class=""govuk-body""></p><h2 class=""govuk-heading-l"">Technical information about this website's accessibility</h2><p class=""govuk-body""></p><p class=""govuk-body"">Education and Skills Funding Agency is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

</p><h2 class=""govuk-heading-l"">Compliance status</h2><p class=""govuk-body"">

This website is fully compliant with the <a href=""https://www.w3.org/TR/WCAG21/"" title="""" class=""govuk-link"">Web Content Accessibility Guidelines version 2.1 AA standard</a>.

We know some of the content is above the reading age of 9. We will work to improve this.</p><p class=""govuk-body"">

</p><h2 class=""govuk-heading-l"">Preparation of this accessibility statement
</h2><p class=""govuk-body"">This statement was prepared on 22 December 2021. </p><p class=""govuk-body"">

This website was last tested on 13 December 2021. The test was carried out by the Education and Skills Funding Agency (ESFA) development team who built the website.</p><p class=""govuk-body""></p>")
            ),
            new Page("Home",
                "home",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Find training and employment schemes for your business</h1><p class=""govuk-body"">A range of government programmes, are available for employers who are considering hiring employees, offering work experience or upskilling existing staff, some of which offer financial incentives.</p>")
            ),
            new Page("Privacy Notice",
                "privacy-notice",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Privacy notice</h1><h2 class=""govuk-heading-l"">Who we are</h2><p class=""govuk-body"">This website is provided by the Education and Skills Funding Agency
(ESFA) which is a part of the Department for Education (DfE). For the
purpose of data protection legislation, the DfE is the data controller 
for the personal data processed as part of this website.</p><p class=""govuk-body"">We collect certain information or data about you when you use of this website if you 
agree to it. This includes your IP address, details of which version of web browser 
you used, information on you use the site, using cookies and page tagging 
techniques to help us improve the website.</p><p class=""govuk-body"">This helps us to improve the site by monitoring how you use it. We can't personally 
identify you using your data.</p><h2 class=""govuk-heading-l"">Keeping your data secure</h2><p class=""govuk-body"">We won't share your information with any other organisations for marketing, market 
research or commercial purposes, and we don't pass on your details to other 
websites.</p><h2 class=""govuk-heading-l"">Disclosing your information</h2><p class=""govuk-body"">We may pass on your information if we have a legal obligation to do so, or if we have
to enforce or apply our terms of use and other agreements. This includes exchanging
information with other government departments for legal reasons.</p><h2 class=""govuk-heading-l"">Links to other websites</h2><p class=""govuk-body"">This website contains links to other websites. This privacy policy only applies to this 
website. If you go to another website from this one, read the privacy policy on that 
website to find out what it does with your information.</p><h2 class=""govuk-heading-l"">Following a link to this website from another website</h2><p class=""govuk-body"">If you come to this website from another website, we may receive personal 
information about you from the other website. You should read the privacy policy of 
the website you came from to find out more about this.</p>")
            ),
        };
        private IEnumerable<CaseStudyPage>? _caseStudyPages;
        public IEnumerable<CaseStudyPage> CaseStudyPages => _caseStudyPages ??= new CaseStudyPage[]
        {
        };

        private ContactPage? _contactPage;
        public ContactPage? ContactPage => _contactPage ??= new ContactPage() { ContactPageTitle = "Contact Page" };

        private SchemeComparison? _schemeComparison;
        public SchemeComparison? SchemeComparison => _schemeComparison ??= new SchemeComparison() 
        {

            SchemeComparisonTitle = "Scheme Comparison",

            SchemeComparisonActionButtonText = "Clear filters and show all schemes",

            SchemeComparisonTitleColumnHeading = "Scheme name",

            SchemeComparisonRecruitOrTrainHeading = "Recruit new staff or train existing staff",

            SchemeComparisonAgeHeading = "Age criteria",

            SchemeComparisonCostHeading = "Cost",

            SchemeComparisonDurationHeading = "Duration",

        };

        private BetaBanner? _betaBanner;
        public BetaBanner? BetaBanner => _betaBanner ??= new BetaBanner()
        {

            BetaBannerID = "employer-schemes-beta-banner",

            BetaBannerTitle = "Employer schemes beta banner"

        };

        private InterimFooterLinks? _interimFooterLinks;
        public InterimFooterLinks InterimFooterLinks => _interimFooterLinks ??= new InterimFooterLinks()
        {

            InterimFooterLinksTitle = "Interim Footer - Apprenticeship schemes footer",

            InterimFooterLinksID = "employer-schemes-footer",

            InterimFooterLinksPrimarySectionTitle = "Our policies",

            InterimFooterLinksSecondarySectionTitle = "Sites for other UK countries",

            InterimFooterLinksPrimarySectionLinks = new List<InterimFooterLink>()
            {

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Accessibility Statement",

                    InterimFooterLinkSource = "/page/accessibility-statement",

                    InterimFooterLinkText = "Accessibility",

                    InterimFooterLinkOrder = 1

                },

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Cookies",

                    InterimFooterLinkSource = "/page/cookies",

                    InterimFooterLinkText = "Cookies",

                    InterimFooterLinkOrder = 2

                },

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Privacy",

                    InterimFooterLinkSource = "https://www.gov.uk/government/organisations/department-for-education/about/personal-information-charter",

                    InterimFooterLinkText = "Privacy",

                    InterimFooterLinkOrder = 3

                },

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Contact",

                    InterimFooterLinkSource = "/contact/index",

                    InterimFooterLinkText = "Contact",

                    InterimFooterLinkOrder = 4

                }

            }, 

            InterimFooterLinksSecondarySectionLinks = new List<InterimFooterLink>()
            {

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Scotland",

                    InterimFooterLinkSource = "https://findbusinesssupport.gov.scot/service/training/get-funded-training-for-new-or-existing-staff-through-apprenticeships",

                    InterimFooterLinkText = "Scotland",

                    InterimFooterLinkOrder = 1

                },

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Wales",

                    InterimFooterLinkSource = "https://careerswales.gov.wales/employers",

                    InterimFooterLinkText = "Wales",

                    InterimFooterLinkOrder = 2

                },

                new InterimFooterLink()
                {

                    InterimFooterLinkTitle = "InterimFooterLink - Northern Ireland",

                    InterimFooterLinkSource = "https://www.nibusinessinfo.co.uk/",

                    InterimFooterLinkText = "Northern Ireland",

                    InterimFooterLinkOrder = 3

                }

            }

        };

    }
}
